### ISSUE TITLE
config File location error

### ISSUE THREAD

**Issue by licongge** [tzhu-bio/CAT_snakemake#6]
Hello, I'm trying to use the process of cisdynet. However, the following error message appears.

WorkflowError in line 25 of /data/DATAprocess/licg/software/cisDynet_snakemake/atacqc/cisDynet_snakemake.py:
Config file config.yaml not found.
  File "/data/DATAprocess/licg/software/cisDynet_snakemake/atacqc/cisDynet_snakemake.py", line 25, in <module>

But I didn't change the location of the config.yaml file. So, what do I need to modify next?

**Comment by tzhu-bio** [comment]
Make sure config.yaml and cisDynet_snakemake.py are in the same folder.

**Comment by licongge** [comment]
Thanks. I have solved the above problems. However, the following error occurred when running job5.
![Uploading 1711433690549.png…]()

**Comment by licongge** [comment]
|---The current work directory is/data/DATAprocess/licg/formative/ATAC/result
ESC[33mJob counts:
        count   jobs
        1       Sorted_by_name
        1ESC[0m
[bam_sort_core] merging from 25 files and 5 in-memory blocks...
[bam_sort_core] merging from 25 files and 5 in-memory blocks...
[bam_sort_core] merging from 35 files and 5 in-memory blocks...
[bam_sort_core] merging from 35 files and 5 in-memory blocks...
[E::hts_open_format] Failed to open file -@
samtools idxstats: failed to open "-@": No such file or directory
ESC[32m[Tue Mar 26 06:00:54 2024]ESC[0m
ESC[31mError in rule Stat:ESC[0m
ESC[31m    jobid: 0ESC[0m
ESC[31m    output: sort/N_T_P_sorted_raw.bam, temp_file/N_T_P_idxstats.txtESC[0m
ESC[31mESC[0m
ESC[31mRuleException:
CalledProcessError in line 186 of /data/DATAprocess/licg/formative/ATAC/result/cisDynet_snakemake.py:
Command 'set -euo pipefail;  /usr/local/anaconda3/envs/epigenetic/bin/samtools sort -@ 5 raw_bam/N_T_P_raw.bam -o sort/N_T_P_sorted_raw.bam && /usr/local/anaconda3/envs/epigenetic/bin/samtools index sort/N_T_P_sorted_raw.bam && /usr/local/anaconda3/envs/epigenetic/bin/samtools idxstats -@ 5 sort/N_T_P_sorted_raw.bam |cut -f1,3 > temp_file/N_T_P_idxstats.txt' returned non-zero exit status 1.
  File "/usr/local/anaconda3/envs/cisDynet_pipeline/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2326, in run_wrapper
  File "/data/DATAprocess/licg/formative/ATAC/result/cisDynet_snakemake.py", line 186, in __rule_Stat
  File "/usr/local/anaconda3/envs/cisDynet_pipeline/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 568, in _callback
  File "/usr/local/anaconda3/envs/cisDynet_pipeline/lib/python3.8/concurrent/futures/thread.py", line 57, in run
  File "/usr/local/anaconda3/envs/cisDynet_pipeline/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 554, in cached_or_run
  File "/usr/local/anaconda3/envs/cisDynet_pipeline/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 2357, in run_wrapperESC[0m
ESC[31mExiting because a job execution failed. Look above for error messageESC[0m
[Tue Mar 26 06:00:58 2024]
Finished job 10.
8 of 48 steps (17%) done

**Comment by tzhu-bio** [comment]
I think it's a samtools version issue, please try samtools 1.9 first.

**Comment by licongge** [comment]
Hello, the above problem has been solved, but the following error occurred in job0. Secondly, the error does not seem to affect the program to continue running (for example data).

Traceback (most recent call last):
  File "/data/DATAprocess/licg/software/cisDynet_snakemake/atacqc//cal_mapping_rate.py", line 14, in <module>
    out.write(name + '\t' + str(round(float(line.strip().split('(')[1].split(':')[0].rstrip(' %'))/100.0,3)) + '\n')
IndexError: list index out of range
ESC[32m[Wed Mar 27 01:51:47 2024]ESC[0m
ESC[31mError in rule Cal_mapping_rate:ESC[0m
ESC[31m    jobid: 0ESC[0m
ESC[31m    output: temp_file/N_T_P_mapping_rate.txt, temp_file/N_T_P_flagstat.txtESC[0m

**Comment by licongge** [comment]
I will get the following error if I continue to run.

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /data/DATAprocess/licg/formative/ATAC/result/.snakemake/log/2024-03-27T015002.425436.snakemake.log

**Comment by tzhu-bio** [comment]
This should also be a version issue with one of the libraries, make sure you use the environment parameters I provided. You can try running the cal_mapping_rate.py script alone to dedug.

**Comment by licongge** [comment]
If this is undesired use the flag apply_strand_suffix=False.
To turn off the warning set apply_strand_suffix to True or False.
/data/DATAprocess/licg/software/cisDynet_snakemake/atacqc//cal_tss.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead
See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dis_fliter_for['new_distance']=dis_fliter_for['Start']-dis_fliter_for['Start_b']
/data/DATAprocess/licg/software/cisDynet_snakemake/atacqc//cal_tss.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead
See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dis_fliter_rev['new_distance']=dis_fliter_rev['Start_b']-dis_fliter_rev['Start']




/data/DATAprocess/licg/software/cisDynet_snakemake/atacqc//plot_frag_tss.py:50: MatplotlibDeprecationWarning: Auto-removal of overlapping axes is deprecated since 3.6 an
d will be removed two minor releases later; explicitly call ax.remove() as needed.
  plt.subplot(1,2,1)
/data/DATAprocess/licg/software/cisDynet_snakemake/atacqc//plot_frag_tss.py:51: FutureWarning:
`shade` is now deprecated in favor of `fill`; setting `fill=True`.
This will become an error in seaborn v0.14.0; please update your code.
  sns.kdeplot(data=frag_size, x="len",shade=True,common_norm=False,alpha=.8, linewidth=0,color="#585EAA")





[31mMissingOutputException in line 377 of /data/DATAprocess/licg/formative/ATAC/result/cisDynet_snakemake.py:
Job Missing files after 5 seconds:
multiqc/multiqc_report.html
This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait.
Job id: 0 completed successfully, but some output files are missing. 0
  File "/usr/local/anaconda3/envs/cisDynet_pipeline/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 583, in handle_job_success
  File "/usr/local/anaconda3/envs/cisDynet_pipeline/lib/python3.8/site-packages/snakemake/executors/__init__.py", line 252, in handle_job_successESC[0m
ESC[31mExiting because a job execution failed. Look above for error messageESC[0m

**Comment by licongge** [comment]
I ran in the cisDynet_pipeline environment and confirmed the versions of all packages in cisDynet_env.yaml. But the error is as follows.
In addition, running samtools1.9 has the following problems.
[W::hts_idx_load3] The index file is older than the data file: q30/Naive_B_q30.bam.bai

**Comment by tzhu-bio** [comment]
This does not affect the continued running of pipeline.

**Comment by licongge** [comment]
TOBIAS 0.16.1
multiqc 1.21

# TOBIAS 0.16.1 BINDetect
2024-04-02 08:49:05 (1797618) [INFO]    ----- Processing input data -----
2024-04-02 08:49:05 (1797618) [INFO]    Checking reading/writing of files
2024-04-02 08:49:05 (1797618) [INFO]    Reading peaks
2024-04-02 08:49:05 (1797618) [INFO]    - Found 48218 regions in input peaks
2024-04-02 08:49:05 (1797618) [INFO]    - Merged to 48218 regions
2024-04-02 08:49:05 (1797618) [INFO]    Checking for match between --peaks and --fasta/--signals boundaries
2024-04-02 08:49:05 (1797618) [INFO]    - Comparing peaks to /data/DATAprocess/licg/software/ref/hg19/hg19.fa
2024-04-02 08:49:05 (1797618) [INFO]    - Comparing peaks to ATACorrect/N_T_P_footprints.bw
2024-04-02 08:49:05 (1797618) [ERROR]   Chromosome for region "chrM     122     3691" is not found in list of available chromosomes

Please how do I resolve the above error?

**Comment by tzhu-bio** [comment]
This is a TOBIAS issue, not a cisDynet issue.

**Comment by licongge** [comment]
Is it the version?

**Comment by tzhu-bio** [comment]
I am using 0.15.1.

**Comment by licongge** [comment]
Hello, my sample is Primed pluripotent stem cells, using the reference genome of hg38 UCSC. Why is the comparison rate so low?

26605950 reads; of these:
  26605950 (100.00%) were paired; of these:
    14370485 (54.01%) aligned concordantly 0 times
    2530017 (9.51%) aligned concordantly exactly 1 time
    9705448 (36.48%) aligned concordantly >1 times
45.99% overall alignment rate

**Comment by tzhu-bio** [comment]
It should be that your sample is contaminated. You can check the reads that failed to match up at NCBI.

**Comment by licongge** [comment]
https://jaspar.genereg.net/download/data/2022/CORE/JASPAR2022_CORE_non-redundant_pfms_meme.txt

Hello, is the above URL the source file of motif_jaspar or just a format reference?

**Comment by tzhu-bio** [comment]
Just for reference, you can download the corresponding meme files from this database.

**Comment by licongge** [comment]
I'm Sorry, I need to confirm to you, is the input file of this step a raw Count file?
Your exsample file (Diff_Analysis_Example) is not a Count file.

![1713838657888](https://github.com/tzhu-bio/cisDynet_snakemake/assets/157385817/70c83e3f-256d-41c2-ae9d-c993c3da7d5b)

**Comment by licongge** [comment]
After downloading the meme files of the corresponding species, do I need to process them into the following file formats?
![image](https://github.com/tzhu-bio/cisDynet_snakemake/assets/157385817/c0b25398-31c3-4614-8630-b19d5cdb29b2)

**Comment by tzhu-bio** [comment]
The input file here is not count data, just use the quantitative data obtained earlier (**4.3 Quantification**).

**Comment by tzhu-bio** [comment]
https://jaspar.genereg.net/download/data/2022/CORE/JASPAR2022_CORE_non-redundant_pfms_meme.txt
Just keep it in the same format as this file.

**Comment by licongge** [comment]
RNA_TPM_Norm_Data.tsv       Is it the RSEM_TPM_Results.txt file after running rna_snakemake?
![1713881028132](https://github.com/tzhu-bio/cisDynet_snakemake/assets/157385817/d32990e7-dc9a-4c5c-8653-4e6552feef30)

**Comment by tzhu-bio** [comment]
Yes, you are right.

**Comment by licongge** [comment]
Is hg19_gene_standard.bed generated from gtf file? The reference genome version for my bulk RNAseq is hg38, and the reference genome version for ATAC data is hg19. There is an error in integrating data to study the regulatory network, which is related to the reference genome version?

![1713950751014](https://github.com/tzhu-bio/cisDynet_snakemake/assets/157385817/16621e60-9e7e-46a8-95e7-ac87b112f525)

**Comment by tzhu-bio** [comment]
Yes, hg19_gene_standard.bed was generated from gtf file. You should use the same genome version when using cisDynet.

**Comment by licongge** [comment]
Excuse me, I have downloaded the reference genome of UCSC platform at present. Do I need hg19.knownGene.gtf.gz, hg19.ensGene.gtf.gz or hg19.ncbiRefSeq.gtf.gz to annotate the file?

![1714011487963](https://github.com/tzhu-bio/cisDynet_snakemake/assets/157385817/370b621d-7d1d-47ef-b302-dda3704edc4c)
